"""
config.py
=========
Configuración centralizada del detector de música generada por IA:
- Catálogo de herramientas de IA musical conocidas (para el análisis de metadatos).
- Pistas genéricas de IA (cuando no se identifica una herramienta específica).
- Umbrales de clasificación final.
- Pesos usados para combinar las distintas capas de decisión.
"""

# ---------------------------------------------------------------------------
# Catálogo de herramientas de generación musical por IA.
# La clave es el identificador "bonito" que se reporta en la respuesta,
# el valor es la lista de sub-cadenas (en minúsculas) que se buscan dentro
# de los metadatos del archivo (title, artist, album, comment, encoder, genre...).
# ---------------------------------------------------------------------------
AI_TOOL_SIGNATURES = {
    "Suno": ["suno", "suno ai", "suno.ai", "sunoai"],
    "Sondo": ["sondo"],
    "Gemini": ["gemini", "google gemini"],
    "Mureka": ["mureka"],
    "AIVA": ["aiva", "aiva technologies"],
    "Mubert": ["mubert"],
    "Soundful": ["soundful"],
    "Soundraw": ["soundraw"],
    "LANDR": ["landr"],
    "Beatoven": ["beatoven", "beatoven.ai"],
    "Moises": ["moises", "moises.ai", "moisesai"],
    "Undio": ["undio"],
    "MusicGPT": ["musicgpt", "music gpt"],
    "ElevenLabs Music": ["elevenlabs music", "elevenlabs-music"],
    "ElevenLabs": ["elevenlabs", "eleven labs"],
    "MusicCreator AI": ["musiccreator ai", "music creator ai", "musiccreator"],
    "AISong": ["aisong", "ai song generator", "aisonggenerator"],
    "Vidnoz AI Generador": ["vidnoz", "vidnoz ai"],
    "Music Muse": ["music muse", "musicmuse"],
    "Song.do": ["song.do", "songdo"],
    "Loudly": ["loudly", "loudly.ai"],
    "Musicfui": ["musicfui"],
    "AIsongMarker": ["aisongmarker", "ai song marker"],
    "AIMusicGen": ["aimusicgen", "ai music gen"],
    "Amper Music": ["amper music", "amper"],
    "Canva": ["canva", "canva ai music"],
    "BeatPopAi":["beatpopai","beatpop","beatpop.ai","beatpop ai "]
}

# Pistas genéricas: cuando aparecen términos que sugieren IA pero no
# identifican una herramienta puntual del catálogo anterior.
GENERIC_AI_HINTS = [
    "ai generated", "generated by ai", "ai-generated", "artificial intelligence",
    "inteligencia artificial", "generado por ia", "hecho con ia", "ia generativa",
    "text-to-music", "texto a musica", "texto a música", "synthetic voice",
    "voz sintetica", "voz sintética", "ai music", "musica ia", "música ia",
    "aigc", "neural music", "modelo generativo", "generative music",
]

# Campos de metadatos que se inspeccionan durante el análisis.
METADATA_FIELDS_TO_SCAN = [
    "title", "artist", "album", "albumartist", "genre",
    "comment", "encoder", "encodedby", "software", "copyright", "publisher",
]

# ---------------------------------------------------------------------------
# Umbrales de clasificación final (escala 0-100).
# ---------------------------------------------------------------------------
CLASSIFICATION_THRESHOLDS = [
    (20, "Humano"),
    (40, "Probablemente Humano"),
    (60, "Indeterminado"),
    (80, "Probablemente generado por IA"),
    (101, "Generado por IA"),
]

# ---------------------------------------------------------------------------
# Pesos de combinación de capas de decisión.
# ---------------------------------------------------------------------------
WEIGHTS = {
    # Cuando los metadatos detectan una herramienta específica de IA,
    # su peso domina el score final, pero aún se combina un poco con el
    # análisis de contenido para dar contexto (no anula por completo).
    "metadata_conclusive_metadata_weight": 0.85,
    "metadata_conclusive_content_weight": 0.15,

    # Cuando Shazam reconoce la canción como una grabación existente,
    # esto es evidencia fuerte (pero no absoluta) de origen humano.
    "shazam_conclusive_shazam_weight": 0.70,
    "shazam_conclusive_content_weight": 0.30,

    # Ponderación interna del análisis acústico + letras (fuzzy)
    "acoustic_weight": 0.65,
    "lyrics_weight": 0.35,
}

# Duración máxima (segundos) de audio analizada acústicamente, por rendimiento.
MAX_ANALYSIS_DURATION_SECONDS = 60

# Score base asignado cuando Shazam reconoce la pista (antes de mezclar
# con el resto de las señales). Bajo porque una canción reconocida por
# Shazam suele ser una grabación comercial/humana ya publicada.
SHAZAM_RECOGNIZED_BASE_SCORE = 12.0

# Score asignado cuando se detecta una herramienta específica de IA en metadatos.
METADATA_TOOL_DETECTED_SCORE = 97.0
# Score asignado cuando solo se detecta una pista genérica de IA.
METADATA_GENERIC_HINT_SCORE = 68.0
